events{

}

http{

    upstream node-server{
        server node-server-1:3000;
        server node-server-2:3000;
        server node-server-3:3000;
    }

    server{
        listen 80;

        location / {
            proxy_pass http://node-server;
        }
    }

}

