services:
  nginx:
    image: nginx:latest
    ports:
      - "8000:80"
#     volumes:
#       - ./nginx.conf:/etc/nginx/nginx.conf # Nginx configuration file - it mainly contains the rules for routing the traffic to the backend servers
#     networks:
#       - loadbalancer-network # The network that the nginx container will be connected to

# networks:
#   loadbalancer-network:
#     driver: bridge
    # driver: bridge is used to create a bridge network - it is a network that allows the containers to communicate with each other
